### ISSUE TITLE
还需要实现的功能

### ISSUE THREAD

**Issue by EVandAK** [Starrier/iShare#23]
详细文章页面里：
- [x] 1.“喜欢文章”，“收藏文章”，“分享文章”按钮；
- [x] 2.“显示时间”；
- [x] 3.作者身份下的“原创”，“粉丝，”“喜欢”人数计数；
- [x] 4.出现的标签的文章页面；
- [x] 5.出现的文章标题相对应的文章页面；

主页页面里：
- [x] 1.页面实现；
- [x] 2.实现时候的错位问题（我在努力的解决）；

**Comment by Starriers** [comment]
@EVandAK  看下你目前 实现的功能 然后告诉我

**Comment by EVandAK** [comment]
主页页面里：
1，2已经实现

详细文章页面里：
4，5已经实现
